language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
before_install:
  - composer self-update
  - composer install
  - touch ./storage/database-testing.sqlite
  - php artisan migrate --database=testing

script: "phpunit"
