language: php
php:
  - 5.5
  - 5.6
  - 7
  - hhvm
before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist
  - php artisan key:generate
  - touch storage/database-testing.sqlite
  - php artisan migrate --database=testing --force
script:
  - phpunit
